package com.lianqu1990.morphling.dao.jpa.entity;
// Generated 2017-10-22 15:58:56 by Hibernate Tools 4.3.5.Final

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.*;

import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Menu generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor

@Entity
@DynamicInsert
@DynamicUpdate
@Table(name = "menu")
public class Menu implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private Integer id;
    private String text;
    private int type;
    private String icon;
    private String route;
    private String html;
    private String translate;
    private int parent;
    private String urlMatches;
    private int ordered;


    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "text", nullable = false, length = 100)
    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @Column(name = "type", nullable = false)
    public int getType() {
        return this.type;
    }

    public void setType(int type) {
        this.type = type;
    }

    @Column(name = "icon", nullable = false)
    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    @Column(name = "route", nullable = false)
    public String getRoute() {
        return this.route;
    }

    public void setRoute(String route) {
        this.route = route;
    }

    @Column(name = "html", nullable = false, length = 5000)
    public String getHtml() {
        return this.html;
    }

    public void setHtml(String html) {
        this.html = html;
    }

    @Column(name = "translate", nullable = false)
    public String getTranslate() {
        return this.translate;
    }

    public void setTranslate(String translate) {
        this.translate = translate;
    }

    @Column(name = "parent", nullable = false)
    public int getParent() {
        return this.parent;
    }

    public void setParent(int parent) {
        this.parent = parent;
    }

    @Column(name = "url_matches", nullable = false, length = 1000)
    public String getUrlMatches() {
        return this.urlMatches;
    }

    public void setUrlMatches(String urlMatches) {
        this.urlMatches = urlMatches;
    }

    @Column(name = "ordered", nullable = false)
    public int getOrdered() {
        return this.ordered;
    }

    public void setOrdered(int ordered) {
        this.ordered = ordered;
    }

}
